name: abs_flutter
description: "An ABS app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.7

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_platform_widgets: ^7.0.1
  openapi_generator_annotations: ^5.0.2
  dio: ^5.5.0+1
  intl: ^0.19.0
  go_router: ^12.1.3 # 13.x and up not working due to https://github.com/flutter/flutter/issues/140586
  quickalert: ^1.1.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  abs_api:
    path: ./api/abs_api
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  connectivity_plus: ^6.0.3
  just_audio: ^0.9.39
  audio_service: ^0.18.15
  package_info_plus: ^8.0.1
  just_audio_windows: # ^0.2.1 Waiting for update
    path: ./modules/just_audio_windows
  audio_service_mpris: ^0.1.5
  just_audio_media_kit: 2.0.3
  flutter_settings_screens: ^0.3.4
  device_info_plus: ^10.1.1
  window_manager: ^0.3.9
  fl_chart: ^0.68.0
  background_downloader: ^8.5.2
  permission_handler: ^11.3.1 # Nuget not found
  path: ^1.9.0
  hooks_riverpod: ^2.5.1
  sensors_plus: ^6.0.1
  vibration: ^1.9.0
  url_launcher: ^6.3.0
  flutter_widget_from_html_core: ^0.15.1
  flutter_localizations:
    sdk: flutter
  sembast: ^3.7.2
  path_provider: ^2.1.4
  sembast_web: ^2.4.0+2

  flutter_hooks: any
  uuid: any
  collection: any
  built_collection: any
  built_value: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  openapi_generator: ^5.0.2
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12
  analyzer: ^6.5.0
  msix: ^3.16.7
  icons_launcher: ^2.1.7

dependency_overrides:
  meta: ^1.14.0
  media_kit: 1.1.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/library_icons/

  generate:
    true

flutter_intl:
  enabled: true
  use-escaping: true
  main_locale: en
  class_name: S

msix_config:
  display_name: Audiobookshelfly
  publisher_display_name: Vito0912
  identity_name: vito0912.audiobookshelf.flutter
  msix_version: 1.1.0.0
  capabilities: internetClient
  languages: en-us
  install_certificate: false

icons_launcher:
  image_path: "assets/images/logo/logo_blue_big_abs.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/logo/logo_blue_big_abs.png"
      adaptive_background_color: "#2a5bb8"
      adaptive_foreground_image: "assets/images/logo/logo_abs.png"
      adaptive_round_image: "assets/images/logo/logo_abs.png"
      adaptive_monochrome_image: "assets/images/logo/logo_black_abs.png"
    ios:
      enable: true
      image_path: "assets/images/logo/logo_blue_big_abs.png"
    web:
      enable: true
      image_path: "assets/images/logo/logo_big_black_abs.png"
      favicon_path: "assets/images/logo/logo_big_black_abs.png"
    macos:
      enable: true
      image_path: "assets/images/logo/logo_blue_big_abs.png"
    windows:
      enable: true
      image_path: "assets/images/logo/logo_blue_big_abs.png"
    linux:
      enable: true
      image_path: "assets/images/logo/logo_blue_big_abs.png"