name: audiobookshelfly
version: 1.4.0
summary: An ABS app
description: Client for Audiobookshelf

confinement: strict
base: core24
grade: stable

slots:
  dbus-abs_flutter:
    interface: dbus
    bus: session
    name: org.bar.abs_flutter

apps:
  audiobookshelfly:
    command: abs_flutter
    extensions: [gnome]
    plugs:
      - network
    slots:
      - dbus-abs_flutter
parts:
  audiobookshelfly:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-0
      - libjsoncpp-dev