name: buchable
base: core22
version: '1.7.4'
summary: The unofficial cross-platform app for Audiobookshelf
description: |
  Buchable is a third-party client for the Audiobookshelf server, designed to 
  maintain a single codebase for multiple OS platforms. The app offers features 
  like fast account switching, advanced caching, offline support, and more.

grade: stable
confinement: strict

architectures:
  - amd64

apps:
  buchable:
    command: abs_flutter
    extensions: [gnome]
    plugs:
      - network
      - audio-playback
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - unity7
      - gsettings
      - mpris
    slots:
      - dbus-buchable
    desktop: usr/share/applications/buchable.desktop
    common-id: de.vito.absapp.abs_flutter
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
      MPV_HOME: $SNAP_USER_DATA/.mpv
      LIBMPV_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libmpv.so.1
      MEDIA_KIT_OVERRIDE_LIBMPV_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libmpv.so.1

slots:
  dbus-buchable:
    interface: dbus
    bus: session
    name: de.vito.absapp.abs_flutter

parts:
  buchable:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - clang
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - libmpv-dev
      - libsecret-1-dev
      - liblzma-dev
      - libstdc++-12-dev
      - libayatana-appindicator3-dev
      - xdg-user-dirs
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libswresample-dev
      - ffmpeg
    stage-packages:
      - libsecret-1-0
      - libmpv1
      - mpv
      - libayatana-appindicator3-1
      - libgtk-3-0
      - xdg-user-dirs
      - libavcodec58
      - libavformat58
      - libavutil56
      - libswresample3
      - ffmpeg
    override-prime: |
      craftctl default
      mkdir -p usr/share/applications
      mkdir -p usr/share/icons/hicolor/256x256/apps
      cp $SNAPCRAFT_PROJECT_DIR/snap/gui/buchable.desktop usr/share/applications/
      cp $SNAPCRAFT_PROJECT_DIR/snap/gui/buchable.png usr/share/icons/hicolor/256x256/apps/
      mkdir -p $SNAPCRAFT_PRIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET