name: Flutter Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Act dependencies
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install sudo -y

      - name: Install dependencies
        run: |
          sudo apt-get update -o Acquire::ForceIPv4=true
          sudo apt-get install -y wget curl xz-utils git bash unzip bash zip

      - name: Install packages for Linux build
        run: |
          sudo apt-get install -y snapd -o Acquire::ForceIPv4=true
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa -o Acquire::ForceIPv4=true
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev -o Acquire::ForceIPv4=true
          sudo apt-get install -y liblzma-dev libgtk-3-0 libblkid1 liblzma5 -o Acquire::ForceIPv4=true

      - name: Install package requirements for Flutter
        run: |
          sudo apt-get install -y libsecret-1-dev libjsoncpp-dev

      - name: Install jq
        run: |
          wget -O jq https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64
          chmod +x ./jq
          mv jq /usr/local/bin

      - name: Add exception
        run: git config --global --add safe.directory /opt/hostedtoolcache/flutter/*

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - uses: snapcore/action-build@v1
        id: snapcraft
        with:
          snapcraft-args: --verbosity debug

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: snapcraft-logs
          path: ~/.local/state/snapcraft/log/*.log

      - name: clean
        run: flutter clean

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Linux
        run: flutter build linux

      - name: Move and rename build
        run: |
          zip -r audiobookshelfly-linux.zip build/linux/x64/release/bundle/abs_flutter

      - name: Upload linux build
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build-artifacts
          path: |
            audiobookshelfly-linux.zip
